// Import polyfills for fetch required by msgraph-sdk-javascript.
require("isomorphic-fetch");
const teamsfxSdk = require("@microsoft/teamsfx");
const fetch = require("node-fetch"); // to install, use npm install node-fetch@2
const { Connection, Request } = require('tedious');

const config = require("../config");
const msal = require('@azure/msal-node');

/**
 * @param {Context} context - The Azure Functions context object.
 * @param {HttpRequest} req - The HTTP request.
 * @param {teamsfxContext} { [key: string]: any; } - The context generated by teamsfx binding.
 */
module.exports = async function (context, req, teamsfxContext) {
    context.log("HTTP trigger function processed a request.");
    let route = context.bindingData.route; // Get api route name
    let method = req.method.toLowerCase();
    let id = context.bindingData.id;

    try {
        // Prepare id token (also auth or sso token).
        const ssoToken = teamsfxContext["AccessToken"];
        if (!ssoToken) {
            return {
                status: 400,
                body: {
                    error: "No access token was found in request header.",
                },
            };
        }

        // get access token through on-behalf-of flow
        let accessToken = await getAccessToken(ssoToken);

        // test
        await getAnalyticsDataForSharepoint(accessToken, req);

        // get access token to call Office365 management API (Audit Sharepoint)
         let accessTokenO365API = await getAccessTokenWithMsal(ssoToken);

        // Test: call office 365 management api
        // 1. subscribe to Audit.Sharepoint
        //  await establishSubToO365(accessTokenO365API)

        // 2. get content blobs
        //   await listAvailableContentO365(accessTokenO365API)



        // Primary routing
        let response;
        let siteresponse;
        switch (method) {
            case "get":
                response = await getRequestHandler(accessToken, route, accessTokenO365API);
                break;
            case "post":
                response = await postRequestHandler(accessToken, route, req);
                break;
            case "put":
                response = await putRequestHandler(route, id);
                break;
            case "delete":
                response = await deleteRequestHandler(route, id);
                break;
        }

        // return a response object to the client
        return {
            status: response.status || 200,
            body: response.data,
            // sitestatus: siteresponse.status || 200,
            // body: siteresponse.data,
        };


    } catch (error) {
        return {
            status: error.status || 500,
            body: {
                error: error.message || "Unable to execute request"
            }
        }
    }


};


async function getAccessTokenWithMsal() {
    const msalConfig = {
        auth: {
            clientId: config.clientId,
            authority: `https://login.microsoftonline.com/${config.tenantId}`,
            clientSecret: config.clientSecret,
            knownAuthorities: [],
        }
    }
    const cca = new msal.ConfidentialClientApplication(msalConfig);
    const clientCredentialRequest = {
        scopes: ["https://microdev.sharepoint.com/.default"],
    };

    try {
        let response = await cca.acquireTokenByClientCredential(clientCredentialRequest)
        console.log("..........msal", response.accessToken)
        return response.accessToken
    } catch (error) {
        // Todo: remove console logs and replace with necessary action
        console.log(">>>>>>>>> error", error)
    }
}

async function getRequestHandler(accessToken, route,  req) {
    try {
        let data, query;
        switch (route) {
            case "consent":
                data = true;
                break;
            case "user":
                data = await getSignedInUserData(accessToken); // get signed in user's Microsoft 365 data
                break;
            case "site":
                data = await getSignedInUserSiteData(accessToken);
                break;
            case "teams":
                data = await getSignedInUserTeamsData(accessToken);
                break;
            case "reports":
                data = await getUserreportsData(accessToken);
                break;
            case "sharepoint":
                data = await getTotalSharepointData(accessToken);
                break;
            case "owners":
                data = await getGroupOwnersData(accessToken);
                break;
            case "members":
                data = await getGroupMembersData(accessToken);
                break;
            case "allusers":
                data = await getAllUsers(accessToken);
                break;
            case "analytics":
                data = await getAnalyticsData(accessToken, req);
                break;
                case "sharepointrest":
                    data = await getsharepointrestData(accessToken);
                    break;
                    case "sharepointanalytics":
                        data = await  getAnalyticsDataForSharepoint(accessToken, req);
                        break;
                   

            // case "restSite":
            //     data = await getUserRestSiteData();
            //     break;
            // case "restYammer":
            //     data = await getUserRestYammerData();
            //     break;

        }

        // if the switch...case statement results in a query, a database call is made
        if (query) {
            try {
                data = await getResultFromDatabase(query);
            } catch (error) {
                throw error;
            }
        }

        return {
            status: 200,
            data: data
        }
    } catch (error) {
        throw { status: 500, message: "Unable to fetch data." };
    }
}



async function postRequestHandler(accessToken, route, req) {
    // logic comes here
    try {
        let data, query;
        let reqbody = req.body
        switch (route) {
            case "postGroup":
                data = await postSignedInUserGroup(accessToken, reqbody); // get signed in user's Microsoft 365 data
                break;
            case "postTeams":
                data = await postSignedInUserTeams(accessToken, reqbody); // get signed in user's Microsoft 365 data

        }

        // if the switch...case statement results in a query, a database call is made
        if (query) {
            try {
                data = await getResultFromDatabase(query);
            } catch (error) {
                throw error;
            }
        }

        return {
            status: 200,
            data: data
        }
    } catch (error) {
        throw { status: 500, message: "Unable to fetch data." };
    }
}

async function putRequestHandler(route, id) {
    // logic comes here
}

async function deleteRequestHandler(route, id) {
    // logic comes here
}

// function to exchange sso token for access token on-behalf-of the user from Azure AD
async function getAccessToken(ssoToken) {
    try {
        const tokenEndpoint = `https://login.microsoftonline.com/${config.tenantId}/oauth2/v2.0/token`;

        let Headers = new fetch.Headers();
        Headers.append('Content-Type', 'application/x-www-form-urlencoded');

        let urlencoded = new URLSearchParams();
        urlencoded.append('grant_type', 'urn:ietf:params:oauth:grant-type:jwt-bearer');
        urlencoded.append('client_id', config.clientId);
        urlencoded.append('client_secret', config.clientSecret);
        urlencoded.append('assertion', ssoToken);
        urlencoded.append('scope', "User.Read User.ReadBasic.All User.Read.All Directory.Read.All Sites.Read.All Team.ReadBasic.All TeamSettings.Read.All Directory.ReadWrite.All Group.ReadWrite.All Team.Create Sites.FullControl.All Reports.Read.All Sites.Read.All");
        urlencoded.append('requested_token_use', 'on_behalf_of');

        let options = {
            method: 'POST',
            headers: Headers,
            body: urlencoded
        };

        let response = await fetch(tokenEndpoint, options);
        if (response.ok) {
            let tokenData = await response.json();
            return tokenData.access_token;
        } else {
            let responseText = await response.text();
            if (JSON.parse(responseText).error === "invalid_grant") {
                throw { status: 401, message: "invalid_grant: You or an administrator needs to consent to required permission(s)." };
            } else {
                throw { status: 400, message: "Unable to get access token." };
            }
        }
    } catch (err) {
        throw { status: err.status || 500, message: (err.status && err.status < 500) ? err.message : "Unable to get access token." };
    }
}

// function to get signed in user's Microsoft 365 data
async function getSignedInUserData(accessToken) {
    let userEndpoint = "https://graph.microsoft.com/v1.0/me/MemberOf/microsoft.graph.group"
    let userOptions = {
        method: 'GET',
        headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-type': 'application/json',
            'Accept': 'application/json',
            'Accept-Charset': 'utf-8',
            'ConsistencyLevel': 'eventual'
        },
    };

    try {
        let response = await fetch(userEndpoint, userOptions);
        if (response.ok) {
            let userData = await response.json();
            return userData;
        } else {
            throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
        }
    } catch (err) {
        throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
    }
}

async function getSignedInUserSiteData(accessToken) {
    let userEndpoint = "https://graph.microsoft.com/v1.0/sites?search=contentclass:STS_Site"
    let userOptions = {
        method: 'GET',
        headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-type': 'application/json',
            'Accept': 'application/json',
            'Accept-Charset': 'utf-8',
            'ConsistencyLevel': 'eventual'
        },
    };

    try {
        let response = await fetch(userEndpoint, userOptions);
        console.log('.....testing this 1')
        if (response.ok) {
            console.log('.....testing this 2')
            let userData = await response.json();
            return userData;
        } else {
            let testerr = await response.text();
            console.log(testerr)
            throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
        }
    } catch (err) {
        console.log('.....testing this', err)
        throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
    }
}
async function getsharepointrestData(accessToken) {
    let userEndpoint = "http://microdev.sharepoint.com/_api/web/lists"
    let userOptions = {
        method: 'GET',
        headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-type': 'application/json;odata=verbose',
            'Accept': 'application/json;odata=verbose',
            'Accept-Charset': 'utf-8',
            'ConsistencyLevel': 'eventual'
        },
    };

    try {
        let response = await fetch(userEndpoint, userOptions);
        if (response.ok) {
            let userData = await response.json();
            console.log('rest site',userEndpoint)
            return userData;
        } else {
            console.log('rest site error')
            throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
        }
    } catch (err) {
        console.log('rest site error 2',err)
        throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
    }
}


async function getSignedInUserTeamsData(accessToken) {
    let userEndpoint = "https://graph.microsoft.com/v1.0/me/joinedTeams"
    let userOptions = {
        method: 'GET',
        headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-type': 'application/json',
            'Accept': 'application/json;',
            'Accept-Charset': 'utf-8',
            'ConsistencyLevel': 'eventual'
        },
    };

    try {
        let response = await fetch(userEndpoint, userOptions);
        console.log('.....testing this 1')
        if (response.ok) {
            console.log('.....testing this 2')
            let userData = await response.json();
            return userData;
        } else {
            let testerr = await response.text();
            console.log(testerr)
            throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
        }
    } catch (err) {
        console.log('.....testing this', err)
        throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
    }
}
// async function getTotalSharepointData(accessToken) {
//     let userEndpoint = "https://graph.microsoft.com/v1.0/sites/microdev.sharepoint.com:/sites/TeamSiteGet"
//     let userOptions = {
//         method: 'GET',
//         headers: {
//             'Authorization': `Bearer ${accessToken}`,
//             'Content-type': 'application/json',
//             'Accept': 'application/json',
//             'Accept-Charset': 'utf-8',
//             'ConsistencyLevel': 'eventual'
//         },
//     };

//     try {
//         let response = await fetch(userEndpoint, userOptions);
//         console.log('.....testing graph 1')
//         if (response.ok) {
//             console.log('.....testing graph 2')
//             let userData = await response.json();
//             return userData;
//         } else {
//             let testerr = await response.text();
//             console.log(testerr)
//             throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
//         }
//     } catch (err) {
//         console.log('.....testing grapherror', err)
//         throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
//     }
// }
async function getGroupOwnersData(accessToken) {
    let userEndpoint = "https://graph.microsoft.com/v1.0/groups/20188c26-d62a-4ba1-bfab-9a8050bf5cc1/owners"
    let userOptions = {
        method: 'GET',
        headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-type': 'application/json',
            'Accept': 'application/json',
            'Accept-Charset': 'utf-8',
            'ConsistencyLevel': 'eventual'
        },
    };

    try {
        let response = await fetch(userEndpoint, userOptions);
        if (response.ok) {
          //  console.log('group owners', response)
            let userData = await response.json();
            return userData;
        } else {
            console.log('group owners error')
            throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
        }
    } catch (err) {
        console.log('group owners error 2')
        throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
    }
}

async function getGroupMembersData(accessToken) {
    let userEndpoint = "https://graph.microsoft.com/v1.0/groups/20188c26-d62a-4ba1-bfab-9a8050bf5cc1/members"
    let userOptions = {
        method: 'GET',
        headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-type': 'application/json',
            'Accept': 'application/json',
            'Accept-Charset': 'utf-8',
            'ConsistencyLevel': 'eventual'
        },
    };

    try {
        let response = await fetch(userEndpoint, userOptions);
        if (response.ok) {
            console.log('group members', response)
            let userData = await response.json();
            return userData;
        } else {
            console.log('group members error')
            throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
        }
    } catch (err) {
        console.log('group members error 2')
        throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
    }
}

async function getAnalyticsData(accessToken, req) {
    try {
        let analyticsData = {};
        let userUpn = req.query?.userUpn ;
        let isEmailRegExp = new RegExp(/^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/);
        let data = await Promise.all([
            getAnalyticsDataForSharepoint(accessToken, userUpn)
        ]);
        if (isEmailRegExp.test(userUpn)) {
            console.log("analytics chart", userUpn)
            data.forEach((analytic, index) => {
                analytic = analytic.find((user) => user["User Principal Name"] === userUpn);
                switch (index) {

                    case 0:
                        analyticsData.sharepoint = analytic;
                        break;
                }
            })
        } else if (userUpn === "All") {
            analyticsData.sharepoint = data[0];
        }

        return {
            status: 200,
            data: analyticsData
        };
    } catch (err) {
        throw { status: 500, message: "Failed to retrieve analytics data." };
    }
}
async function getAnalyticsDataForSharepoint(accessToken, req) {
    let userUpn = req.query?.userUpn || "shina@microdev.onmicrosoft.com";
    let isEmailRegExp = new RegExp(/^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/);

    let sharepointEndpoint = `https://graph.microsoft.com/v1.0/reports/getSharePointActivityUserDetail(period='D180')`;
    let sharepointOptions = {
        method: 'GET',
        headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-type': 'application/json',
            'Accept': 'application/json',
            'Accept-Charset': 'utf-8'
        },
    };

    try {
        let response = await fetch(sharepointEndpoint, sharepointOptions);
        console.log("................", "reached here 1")
        if (response.ok) {
            console.log("................", "reached here 2")
            let sharepointData = await response.text();
            console.log("analytics chart", userUpn)
            sharepointData = convertCSVToArray(sharepointData);

            // filter data to a single user
            if (isEmailRegExp.test(userUpn)) {
                sharepointData = sharepointData.find((user) => user["User Principal Name"] === userUpn);
                console.log("analytics chart>>>>>>>>>>>>>>>>>>>>>>>>", sharepointData)
            } else if (userUpn === "All") {
                sharepointData = sharepointData;
            }
            
            return sharepointData;
        } else {
            console.log("................", "reached here 3")
            throw { status: 500, message: "Failed to retrieve Sharepoint analytics data." };
        }
    } catch (err) {
        throw { status: 500, message: "Failed to retrieve Sharepoint analytics data." };
    }
}

function convertCSVToArray(csvData) {
    try {    // retrieve the csv header as an array
        let header = csvData.slice(0, csvData.indexOf('\n')).trim().split(',')



        // retrieve the body of the csv into one array with each item being a row in the csv
        let body = csvData.slice(csvData.indexOf('\n') + 1).split('\n');



        // merge the header and each row in the body to be an array of objects
        const parsedData = body.map(function (row) {      // split the row string into items in one array
            // that is, ['2023-03-01', '00118923-2cf6-40eb-b6e6-574c11285e25', ...]
            const values = row.trim().split(",");



            // merge row (values) and header into an object
            // that is, { 'Report Refresh Date': '2023-03-01', 'User Id': '00118923-2cf6-40eb-b6e6-574c11285e25', ...}
            const storeKeyValue = header.reduce(function (obj, title, index) { obj[title] = values[index]; return obj; }, {});



            return storeKeyValue;
        });



        return parsedData;
    } catch (err) { throw err; }
}

async function getUserreportsData(accessToken) {
    let userEndpoint = "https://graph.microsoft.com/v1.0/reports/getSharePointActivityFileCounts(period='D180')"
    let userOptions = {
        method: 'GET',
        headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-type': 'text/csv',
            'Accept': 'text/csv',
            'Accept-Charset': 'utf-8',
            'ConsistencyLevel': 'eventual'
        },
    };



    try {
        console.log('testing reports 123', userEndpoint)
        let response = await fetch(userEndpoint, userOptions);
        console.log('testing reports 123', userEndpoint)

        if (response.ok) {
            let userData = await response.text();
            userData = convertCSVToArray(userData);
            // let headers = csvLines[0].split(',');
            console.log("value for csv")
            return userData

        } else {
            console.log('testing reports failure')
            throw { status: 500, message: "Unable to get user's Microsoft 365 data for report." };
        }

    } catch (err) {
        console.log('testing reports failure')
        throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
    }
}
// function to get all users
async function getAllUsers(accessToken) {
    let allUsersEndpoint = "https://graph.microsoft.com/v1.0/users?$top=999&$filter=(onPremisesSyncEnabled eq true OR userType eq 'Member') and accountEnabled eq true&$select=id,mail,displayName,jobTitle,department,userPrincipalName"
    let allUsersOptions = {
        method: 'GET',
        headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-type': 'application/json',
            'Accept': 'application/json',
            'Accept-Charset': 'utf-8'
        },
    };
    try {
        let response = await fetch(allUsersEndpoint, allUsersOptions);
        if (response.ok) {
            let allUsers = await response.json();
            allUsers = allUsers?.value?.sort((a, b) => (a.displayName > b.displayName) ? 1 : ((b.displayName > a.displayName) ? -1 : 0));
            return {
                status: 200,
                data: allUsers
            };
        } else {
            throw { status: 500, message: "Failed to retrieve list of users." };
        }
    } catch (err) {
        throw { status: 500, message: "Failed to retrieve list of users." };
    }
}
async function postSignedInUserGroup(accessToken, reqbody) {
    let userEndpoint = "https://graph.microsoft.com/v1.0/groups"
    let body = {
        description: reqbody.description,
        displayName: reqbody.displayName,
        securityEnabled: reqbody.security,
        groupTypes: [
            'Unified'
        ],
        mailEnabled: true,
        mailNickname: reqbody.displayName.replaceAll(" ", ""),

    };
    let userOptions = {
        method: 'POST',
        headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-type': 'application/json',
            'Accept': 'application/json',
            'Accept-Charset': 'utf-8',
            'ConsistencyLevel': 'eventual'
        },
        body: JSON.stringify(body)
    };

    try {
        let response = await fetch(userEndpoint, userOptions);
        if (response.ok) {
            let userData = await response.json();
            console.log('user data', userData)
            return userData;
        } else {
            let userError = await response.text();
            console.log('error1', userError)
            throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
        }
    } catch (err) {
        console.log('error2', err)
        throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
    }
}

async function postSignedInUserTeams(accessToken, reqbody) {
    let userEndpoint = "https://graph.microsoft.com/v1.0/teams"
    let body = {
        'template@odata.bind': 'https://graph.microsoft.com/v1.0/teamsTemplates(\'standard\')',
        description: reqbody.description,
        displayName: reqbody.displayName
    };
    let userOptions = {
        method: 'POST',
        headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Content-type': 'application/json',
            'Accept': 'application/json',
            'Accept-Charset': 'utf-8',
            'ConsistencyLevel': 'eventual'
        },
        body: JSON.stringify(body)
    };

    try {
        let response = await fetch(userEndpoint, userOptions);
        if (response.ok) {
            let userData = await response.json();
            console.log('user data', userData)
            return userData;
        } else {
            let userError = await response.text();
            console.log('error1', userError)
            throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
        }
    } catch (err) {
        console.log('error2', err)
        throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
    }
}





// async function getSignedInUserData(accessToken) {
//     let userEndpoint = "https://graph.microsoft.com/v1.0/sites"
//     let userOptions = {
//         method: 'GET',
//         headers: {
//             'Authorization': `Bearer ${accessToken}`,
//             'Content-type': 'application/json',
//             'Accept': 'application/json',
//             'Accept-Charset': 'utf-8',
//             'ConsistencyLevel': 'eventual'
//         },
//     };

//     try {
//         let response = await fetch(userEndpoint, userOptions);
//         if (response.ok) {
//             let userData = await response.json();
//             return userData;
//         } else {
//             throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
//         }
//     } catch (err) {
//         throw { status: 500, message: "Unable to get user's Microsoft 365 data." };
//     }
// }

// Create connection to SQL Server database
async function getSQLConnection(teamsfx) {
    const tediousConfig = {
        authentication: {
            options: {
                userName: config.sqlUsername,
                password: config.sqlPassword,
            },
            type: 'default'
        },
        server: config.sqlEndpoint,
        options: {
            database: config.sqlDatabaseName,
            encrypt: true
        }
    };
    const connection = new Connection(tediousConfig);
    return new Promise((resolve, reject) => {
        connection.on('connect', err => {
            if (err) {
                reject(err);
            }
            resolve(connection);
        })

        connection.on('debug', function (err) {
            console.log('debug:', err);
        });

        connection.connect()
    })
}

// Query connected SQL database
async function execQuery(query, connection) {
    return new Promise((resolve, reject) => {
        const res = [];
        const request = new Request(query, (err) => {
            if (err) {
                reject(err);
            }
        });

        request.on('row', columns => {
            const row = {};
            columns.forEach(column => {
                row[column.metadata.colName] = column.value;
            });
            res.push(row)
        });

        request.on('requestCompleted', () => {
            // add request object to response {res, request}
            resolve(res)
        });

        request.on("error", err => {
            reject(err);
        });

        connection.execSql(request);
    })
}

async function getResultFromDatabase(query) {
    try {
        const connection = await getSQLConnection();
        const result = await execQuery(query, connection);
        connection.close(); // close sql database connection after executing query
        return result
    } catch (error) {
        throw (error);
    }
}